# Site settings
title: The Open GApps Project
description: Open GApps is a Google Apps package developed by writing open source buildscripts. All Android versions and platforms supported.
keywords: open gapps, opengapps, android, daily, arm, arm64, x86, x86_64, 4.4, 5.0, 5.1, 6.0, aroma

# Libraries
gfont: https://fonts.googleapis.com
jquery: https://code.jquery.com/jquery-2.2.2.min.js
mdl: https://storage.googleapis.com/code.getmdl.io/1.1.3
pushbullet: https://www.pushbullet.com/channel-popup?tag=

# Variables/Resouces
ga: Google Apps
org: OpenGApps.org
img: /images/
apimg: /images/apple-icon-
animg: \/images\/android-icon-
color: '#009688'
paginate: 5
paginate_path: /blog/page/:num
blogurl: /blog
blogimg: /blog/images/
permalink: /blog/post/:year/:month/:day/:title/

#gems
gems: [jekyll-paginate]

support:
 faq: https://github.com/opengapps/opengapps/wiki/FAQ
 wiki: https://github.com/opengapps/opengapps/wiki
 xdaqa: http://forum.xda-developers.com/showthread.php?t=3124506
 xdadev: http://forum.xda-developers.com/android/software/Open-GApps-t3098071
 gitter: https://gitter.im/opengapps/general
