# Site settings
url: http://opengapps.org
title: The Open GApps Project
description: OpenGApps.org offers information and pre-built packages of The Open GApps Project. The Open GApps Project is an open-source effort to script the automatic generation of up-to-date Google Apps packages. All Android versions and platforms supported.
keywords: open gapps, opengapps, gapps, android, daily, arm, arm64, x86, x86_64, 4.4, 5.0, 5.1, 6.0, 7.0, 7.1, 8.0, kitkat, lollipop, marshmallow, nougat, oreo, aroma, super, stock, full, mini, micro, nano, pico, tvstock
timezone: Europe/Amsterdam

# App settings
app:
  packagename: org.opengapps.app
  versioncode: 16
  md5sum: 773b5031f945b2009af16d7a442c714a
  sha1sum: 9f570801f37b46668f2d0fd535a0cccaabb937ce
  sha1cert: "E8:4C:C1:A4:DC:E7:EF:CA:9F:11:F2:6A:5A:46:38:31:ED:11:DE:B8"
  sha256cert: "21:20:4C:ED:33:63:DA:1D:3D:9A:D9:81:7F:D0:52:EA:E0:AA:78:0E:18:24:F9:A1:01:DB:8F:A8:06:CD:F6:7B"
  checkagain: 259200 # every 72hrs
  minversion: 0
#betaapp:
#  versioncode:
#  md5sum:
#  sha1sum:

# Libraries
gfont: https://fonts.googleapis.com
mdl: https://storage.googleapis.com/code.getmdl.io/1.3.0
mdlcolor: teal-red
pushbullet: https://www.pushbullet.com/channel-popup?tag=
ads: //pagead2.googlesyndication.com/pagead/js/adsbygoogle.js

# Variables/Resouces
ga: Google Apps
org: OpenGApps.org
img: /images/
apimg: /images/apple-icon-
animg: \/images\/android-icon-
color: '#009688'

# Blog
blogurl: /blog
blogimg: /blog/images/
paginate: 5
paginate_path: /blog/page/:num
permalink: /blog/post/:year/:month/:day/:title/
disqus: opengapps.disqus.com

# Plugins (gems have been renamed to plugins)
plugins: [jekyll-paginate]

# Support
support:
 faq: https://github.com/opengapps/opengapps/wiki/FAQ
 wiki: https://github.com/opengapps/opengapps/wiki
 xdaqa: http://forum.xda-developers.com/showthread.php?t=3124506
 xdadev: http://forum.xda-developers.com/android/software/Open-GApps-t3098071
 gitter: https://gitter.im/opengapps/general

# SASS
sass:
 style: compressed
